teams:
  - name: bots
    maintainers:
      - ryjones
    members:
      - hyperledger-bot
  - name: staff
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
  - name: iroha-admin
    maintainers:
      - Cre-eD
    members:
      - BAStos525
      - RamilMus
      - dmitrivenger
      - safinsaf
      - Mingela
      - sorabot
  - name: iroha-contributors
    maintainers:
      - sorabot
    members:
      - troferoller
      - VladislavPopovSR
      - "0x009922"
      - SamHSmith
      - DCNick3
      - Mingela
      - dmitrivenger
      - aoyako
      - mversic
      - s8sato
      - safinsaf
      - takemiyamakoto
      - dima74
  - name: iroha-ios
    maintainers:
      - sorabot
    members:
      - safinsaf
  - name: iroha-java
    maintainers:
      - Mingela
      - mversic
    members:
      - DCNick3
      - a-zorina
      - adaagava
      - arndey
      - dima74
      - gv-timur
      - timofeevmd
      - s8sato
      - alexstroke1
  - name: iroha-java-admin
    maintainers:
      - mversic
      - Mingela
  - name: iroha-javascript
    maintainers:
      - Cre-eD
      - Mingela
    members:
      - "0x009922"
      - BAStos525
      - DCNick3
      - SamHSmith
      - WRRicht3r
      - a-zorina
      - alexstroke1
      - baziorek
      - dima74
      - dmitrivenger
      - mversic
      - outoftardis
      - s8sato
      - sorabot
      - timofeevmd
  - name: iroha-maintainers
    maintainers:
      - Cre-eD
      - Mingela
      - dmitrivenger
    members:
      - troferoller
      - VladislavPopovSR
      - alexstroke1
      - BAStos525
      - a-zorina
      - adaagava
      - baziorek
      - paul-cpp
      - timofeevmd
  - name: iroha-python
    maintainers:
      - Cre-eD
    members:
      - SamHSmith
      - DCNick3
      - a-zorina
      - adaagava
      - baziorek
      - dima74
      - s8sato
      - timofeevmd
      - Mingela
      - alexstroke1
  - name: iroha-rfc-maintainers
    maintainers:
      - mversic
      - Mingela
      - dmitrivenger
    members:
      - "0x009922"
      - alexstroke1
      - DCNick3
      - WRRicht3r
      - a-zorina
      - dima74
      - outoftardis
repositories:
  - name: governance
    teams:
      staff: maintain
    visibility: public
  - name: iroha
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-contributors: maintain
      iroha-ios: maintain
      iroha-java: maintain
      iroha-java-admin: maintain
      iroha-javascript: maintain
      iroha-maintainers: maintain
      iroha-python: maintain
      iroha-rfc-maintainers: maintain
    visibility: public
  - name: iroha-2-docs
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-contributors: write
      iroha-ios: write
      iroha-java: write
      iroha-java-admin: write
      iroha-javascript: write
      iroha-maintainers: maintain
      iroha-python: write
      iroha-rfc-maintainers: write
    visibility: public
  - name: iroha-2-examples
    teams:
      bots: maintain
      iroha-admin: maintain
      iroha-maintainers: maintain
    visibility: public
  - name: iroha-deploy
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-ed25519
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: read
    visibility: public
  - name: iroha-ios
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-ios: maintain
    visibility: public
  - name: iroha-java
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-java: write
      iroha-java-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-javascript
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-javascript: write
      iroha-maintainers: read
    visibility: public
  - name: iroha-news
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: admin
    visibility: public
  - name: iroha-python
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: read
      iroha-python: maintain
    visibility: public
  - name: iroha-rfcs
    teams:
      bots: maintain
      iroha-admin: maintain
      iroha-maintainers: maintain
      iroha-rfc-maintainers: write
    visibility: public
  - name: iroha-config-base
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-wasm-codec
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-ffi
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-crypto
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: const-str
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: const-vec
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
