teams:
  - name: bots
    maintainers:
      - ryjones
    members:
      - hyperledger-bot
  - name: staff
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
  - name: iroha-1-active-devs
    maintainers:
      - ryjones
    members:
      - kuvaldini
  - name: iroha-admin
    maintainers:
      - Cre-eD
    members:
      - safinsaf
      - BAStos525
      - RamilMus
      - dmitrivenger
      - sorabot
      - nxsaken
  - name: iroha-contributors
    maintainers:
      - takemiyamakoto
    members:
      - safinsaf
      - "0x009922"
      - SamHSmith
      - aoyako
      - WRRicht3r
      - modbrin
      - mversic
      - posplaw
      - s8sato
      - sorabot
      - tkyonezu
  - name: iroha-ios
    maintainers:
      - sorabot
    members:
      - safinsaf
      - nvzhu
      - posplaw
      - takemiyamakoto
  - name: iroha-java
    maintainers:
      - s8sato
    members:
      - DCNick3
      - a-zorina
      - adaagava
      - arndey
      - dima74
      - gv-timur
      - horizenight
      - maglighter
      - orangeng
      - timofeevmd
      - Mingela
  - name: iroha-java-admin
    maintainers:
      - mversic
  - name: iroha-javascript
    maintainers:
      - Cre-eD
    members:
      - "0x009922"
      - BAStos525
      - DCNick3
      - Mingela
      - SamHSmith
      - WRRicht3r
      - a-zorina
      - arndey
      - baziorek
      - dima74
      - dmitrivenger
      - f33r0
      - gv-timur
      - horizenight
      - mversic
      - orangeng
      - outoftardis
      - s8sato
      - sorabot
      - stefashkaa
      - takemiyamakoto
      - timofeevmd
      - alexstroke1
  - name: iroha-maintainers
    maintainers:
      - Cre-eD
    members:
      - "0x009922"
      - alexstroke1
      - BAStos525
      - DCNick3
      - Mingela
      - Stukalov-A-M
      - aoyako
      - a-zorina
      - adaagava
      - baziorek
      - dima74
      - dmitrivenger
      - horizenight
      - mversic
      - orangeng
      - outoftardis
      - paul-cpp
      - s8sato
      - takemiyamakoto
      - timofeevmd
      - tkyonezu
      - yamkovoy
  - name: iroha-python
    maintainers:
      - Cre-eD
    members:
      - SamHSmith
      - DCNick3
      - a-zorina
      - adaagava
      - baziorek
      - dima74
      - horizenight
      - igor-egorov
      - orangeng
      - s8sato
      - takemiyamakoto
      - timofeevmd
      - Mingela
  - name: iroha-rfc-maintainers
    maintainers:
      - mversic
    members:
      - "0x009922"
      - alexstroke1
      - DCNick3
      - Mingela
      - WRRicht3r
      - a-zorina
      - dima74
      - outoftardis
repositories:
  - name: governance
    teams:
      staff: maintain
    visibility: public
  - name: iroha
    teams:
      bots: maintain
      iroha-1-active-devs: maintain
      iroha-admin: admin
      iroha-contributors: maintain
      iroha-ios: maintain
      iroha-java: maintain
      iroha-java-admin: maintain
      iroha-javascript: maintain
      iroha-maintainers: maintain
      iroha-python: maintain
      iroha-rfc-maintainers: maintain
    visibility: public
  - name: iroha-2-docs
    teams:
      bots: maintain
      iroha-1-active-devs: maintain
      iroha-admin: admin
      iroha-contributors: write
      iroha-ios: write
      iroha-java: write
      iroha-java-admin: write
      iroha-javascript: write
      iroha-maintainers: maintain
      iroha-python: write
      iroha-rfc-maintainers: write
    visibility: public
  - name: iroha-2-examples
    teams:
      bots: maintain
      iroha-admin: maintain
      iroha-maintainers: maintain
    visibility: public
  - name: iroha-deploy
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-ed25519
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: read
    visibility: public
  - name: iroha-ios
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-ios: maintain
    visibility: public
  - name: iroha-java
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-java: write
      iroha-java-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-javascript
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-javascript: write
      iroha-maintainers: read
    visibility: public
  - name: iroha-news
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: admin
    visibility: public
  - name: iroha-python
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: read
      iroha-python: maintain
    visibility: public
  - name: iroha-rfcs
    teams:
      bots: maintain
      iroha-admin: maintain
      iroha-maintainers: maintain
      iroha-rfc-maintainers: write
    visibility: public
  - name: iroha-config-base
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-wasm-codec
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-ffi
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: iroha-crypto
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: const-str
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
  - name: const-vec
    teams:
      bots: maintain
      iroha-admin: admin
      iroha-maintainers: write
    visibility: public
